### ISSUE TITLE
Q: run as a standalone graphite-web replacement?

### ISSUE THREAD

**Issue by blysik** [go-graphite/carbonapi#216]
Hi,

I'm looking to run a standalone graphite-web replacement.  Can this project do that?  If so, can you explain the necessary config? 

Thanks!

**Comment by Civil** [comment]
You need to have at least two components in place:
1. something that can read whisper files and speak carbonzipper-compatible protocol. Currently that's https://github.com/lomik/go-carbon (preferred and suggested, version should be >= 0.9.0, 'carbonserver' module must be enabled) or https://github.com/grobian/carbonserver (older thing, not recommended)
2. carbonapi itself

In carbonapi's config you should just replace "zipper" parameter with url of a carbonserver (either host + port from go-carbon or standalone carbonserver).

Let's say you have go-carbon installed on server with IP 192.168.0.2, and you've enabled 'carbonserver' module on port 8080, then carbonapi's config should look something like that:
```yaml
# Need to be URL, http or https
# This url specifies the backend or a loadbalancer
#
# Is you are using carbonzipper you should set it to
# zipper's url
#
# If you are using plain go-carbon or graphite-clickhouse
# you should set it to URL of go-carbon's carbonserver module
# or graphite-clickhouse's http url.
zipper: "http://192.168.0.2:8080"
# Listen address, should always include hostname or ip address and a port.
listen: "localhost:8081"
# Max concurrent requests to CarbonZipper
concurency: 20
cache:
   # Type of caching. Valid: "mem", "memcache", "none"
   type: "mem"
   # Cache limit in megabytes
   size_mb: 0
   # Default cache timeout value. Identical to DEFAULT_CACHE_DURATION in graphite-web.
   defaultTimeoutSec: 60
   # Only used by memcache type of cache. List of memcache servers.
   memcachedServers:
       - "127.0.0.1:1234"
       - "127.0.0.2:1235"
# Amount of CPUs to use. 0 - unlimited
cpus: 0
# Timezone, default - local
tz: ""
# If 'true', carbonapi will send requests as is, with globs and braces
# Otherwise for each request it will generate /metrics/find and then /render
# individual metrics.
# true --- faster, but will cause carbonzipper to consume much more RAM.
#
# For some backends (e.x. graphite-clickhouse) this *MUST* be set to true in order
# to get reasonable performance
#
# For go-carbon --- it depends on how you use it.
sendGlobsAsIs: false
# If sendGlobsAsIs is set and resulting response will be larger than maxBatchSize
# carbonapi will revert to old behavir. This allows you to use benifits of passing
# globs as is but keep memory usage in sane limits.
#
# For go-carbon you might want it to keep in some reasonable limits, 100 is good "safe" defaults
#
# For some backends (e.x. graphite-clickhouse) you might want to set it to some insanly high value, like 100000
maxBatchSize: 100
graphite:
    # Host:port where to send internal metrics
    # Empty = disabled
    host: ""
    interval: "60s"
    prefix: "carbon.api"
# Maximium idle connections to carbonzipper
idleConnections: 10
pidFile: ""
# See https://github.com/go-graphite/carbonzipper/blob/master/example.conf#L70-L108 for format explanation
logger:
    - logger: ""
      file: "stderr"
      level: "debug"
      encoding: "console"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
    - logger: ""
      file: "carbonapi.log"
      level: "info"
      encoding: "json"
```
