### ISSUE TITLE
Does not work upstreams.backends in carbonapi.yaml

### ISSUE THREAD

**Issue by greenplace** [go-graphite/carbonapi#277]
In carbonapi.yaml I set:
```
listen: "[::]:9091"
concurency: 20
cache:
   # Type of caching. Valid: "mem", "memcache", "null"
   type: "mem"
   defaultTimeoutSec: 60
upstreams:
    backends:
        - "http://localhost:9090"
logger:
    - logger: ""
      file: "stderr"
      level: "debug"
      encoding: "console"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
    - logger: ""
      file: "carbonapi.log"
      level: "info"
      encoding: "json"
```

but in log I see request on 8080 port:
`2018-01-15T23:05:20.465+0300	INFO	access	request failed	{"handler": "find", "carbonapi_uuid": "be913418-c7d0-4340-8b0a-54679072fde1", "username": "", "url": "/metrics/find?query=*", "peer_ip": "", "peer_port": "", "host": "127.0.0.1:9091", "referer": "http://localhost:3000/datasources/edit/1", "uri": "/metrics/find?query=*", "http_code": 500, "reason": "http.Get: Get http://localhost:8080/metrics/find/?format=protobuf&query=%2A: dial tcp 127.0.0.1:8080: getsockopt: connection refused", "runtime": 0.002769053}`

When I changed graphite-clickhouse port on 8080
carbonapi started working correctly
but I does not changed carbonapi.yaml
