### ISSUE TITLE
panic using reduce\mapSeries functions

### ISSUE THREAD

**Issue by nikita-b** [go-graphite/carbonapi#305]
Hi! I have the problem with last version carbonapi 0.10. When I request this metric:
```
reduce(mapSeries(stats.gauges.production.dedicated.*.master.rooms.*, 4), 'diffSeries', 7, 'limit', 'busy')
```
I get this error:
```
2018-03-20T10:21:16.109Z#011ERROR#011render#011panic during eval:#011{"cache_key": "format=json&from=1521057611&maxDataPoints=960&target=reduce%28mapSeries%28stats.gauges.production.dedicated.host%2A%2A-%2A.master.rooms.%7Blimit%2Cbusy%7D%2C+4%29%2C+%27diffSeries%27%2C+7%2C+%27limit%27%2C+%27busy%27%29&until=1521169840", "reason": "runtime error: invalid memory address or nil pointer dereference", "stack": "main.renderHandler.func3.1\n\t/root/go/src/github.com/go-graphite/carbonapi/http_handlers.go:408\nruntime.call32\n\t/usr/local/go/src/runtime/asm_amd64.s:509\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:491\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:63\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:367\ngithub.com/go-graphite/carbonapi/expr/functions/reduce.(*reduce).Do\n\t/root/go/src/github.com/go-graphite/carbonapi/expr/functions/reduce/function.go:84\ngithub.com/go-graphite/carbonapi/expr.EvalExpr\n\t/root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:52\nmain.renderHandler.func3\n\t/root/go/src/github.com/go-graphite/carbonapi/http_handlers.go:412\nmain.renderHandler\n\t/root/go/src/github.com/go-graphite/carbonapi/http_handlers.go:420\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1918\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2254\ngithub.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/compress.go:146\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1918\ngithub.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/cors.go:51\ngithub.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers.ProxyHeaders.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/proxy_headers.go:59\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src
```

config
```
listen:` "localhost:8081"
concurency: 20
cache:
   type: "mem"
   size_mb: 0
   defaultTimeoutSec: 60
   memcachedServers:
       - "127.0.0.1:1234"
       - "127.0.0.2:1235"
cpus: 0
tz: ""
sendGlobsAsIs: true
maxBatchSize: 100000000
graphite:
    host: ""
    interval: "60s"
    prefix: "carbon.api"
    pattern: "{prefix}.{fqdn}"
idleConnections: 10
pidFile: ""
upstreams:
    buckets: 10
    timeouts:
        global: "50s"
        afterStarted: "30s"
        connect: "10s"
    concurrencyLimit: 0
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100

    backends:
        - "http://localhost:9090"
    graphite09compat: false
expireDelaySec: 10
logger:
    - logger: ""
      file: "stderr"
      level: "debug"
      encoding: "console"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
    - logger: ""
      file: "carbonapi.log"
      level: "info"
      encoding: "json"
```

This problem only appears when I use reduce\mapSeries functions pair.
