### ISSUE TITLE
Intermittent empty respones from carbonapi

### ISSUE THREAD

**Issue by chris-vidgroup** [go-graphite/carbonapi#310]
We run a cluster of 12 graphite servers running grafana, go-carbon, carbonzipper and carbonapi (0.10.0.1) and intermittently receive carbonapi responses that are http status code 200 but that contain no data. Not metrics that are None or 0, the response is just literally no data except the HTTP headers.

We haven't found any obvious references to this behavior happening for others and so we're looking for some assistance in figuring out what's wrong so that we can correct it.

Background and details

We normally query the cluster through a load balancer, but I can replicate the behavior when querying the nodes directly.

If I add the noCache query param to the request, the frequency of those no-data responses goes up significantly.

I set the log level to debug for carbonapi, but that doesn't appear to be providing much more insight. It isn't logging errors for these requests. The requests are logged as "request served", but it appears that different sets of JSON keys are logged so it's hard to determine what the log is telling me.

There is definitely data in the whisper files and the same nodes returning no data will eventually return data successfully after a period of 10 or so seconds. I tried setting expireDelaySec to 0 (it was 10) but it doesn't seem to have eliminated the behavior.

The behavior happens with raw metrics queries as well as if functions are being applied to them.

There's no appreciable iowait (~1% from writes) and disk reads are minimal (most reads seem to be covered by the OS cache).

We did have to disable the trigram index, because it would become pretty large (28gb and trying to grow) and maintaining it was causing 20% iowait for disk reads (was pushing out the file system cache).

**Comment by chris-vidgroup** [comment]
I'm happy to provide configuration details and log information, but I didn't want to dump a flood of data in without some direction on which may be helpful and which is just noise.

**Comment by azhiltsov** [comment]
Usually empty responses happening in out setup in case of timeout. 
Check what do you have in carbonapi config for next settings:
concurency:
sendGlobsAsIs
maxBatchSize
idleConnections
and timeouts
Same relevant questions about zipper config.
carbonapi uses available connections within concurrency limits to send requests to carbonzipper. 
If during find query api discover more metrics than set in maxBatchSize and sendGlobsAsIs is false then it will expand globs and send metric requests one-by one. In case of conservative timeout settings and many metrics after glob expansion it can easily timeout. Zipper has relevant concurrency and timeouts as well.

**Comment by chris-vidgroup** [comment]
Thanks for the response, this is a new cluster to replace an older version so there are a lot of configurations that didn't exist in the previous setup so there's definitely some guesswork and/or defaults in use.

The clusters have 8 cpus and ~60gb of ram.

concurrency: 8
sendGlobsAsIs: false
maxBatchSize: 100
idleConnections: 10

From upstreams
concurrencyLimit: 1000
```
timeouts:
        # Maximum total backend requesting timeout in ms.
        # ( How long we may spend making requests. )
        global: "10s"
        # Timeout, in ms, once the final backend has been contacted.
        # ( [Effectively] How long we'll wait for the slowest response. )
        afterStarted: "2s"
        # Timeout to connect to the server
        connect: "200ms"
```
