### ISSUE TITLE
timeout exceeded error for go-carbon carbonapi_v3_pb backendv2 with non-zero concurrencyLimit

### ISSUE THREAD

**Issue by hnakamur** [go-graphite/carbonapi#448]
I made a set files for docker-compose to reproduce this problem.
https://github.com/hnakamur/carbonapi-go-carbon-docker-compose-example

Here is a step to reproduce the error:

```
git clone https://github.com/hnakamur/carbonapi-go-carbon-docker-compose-example
cd carbonapi-go-carbon-docker-compose-example
docker-compose up
```

The error log:
> carbonapi_1  | 2020-02-19T03:08:41.453Z DEBUG   zipper  have errors     {"type": "protoV3Group", "name": "carbon", "type": "find", "request": ["*"], "error": "timeout exceeded", "errorVerbose": "timeout exceeded\n\ngithub.com/go-graphite/carbonapi/zipper/helper.(*HttpQuery).doRequest\n\t/go/src/github.com/go-graphite/carbonapi/zipper/helper/requests.go:105\ngithub.com/go-graphite/carbonapi/zipper/helper.(*HttpQuery).DoQuery\n\t/go/src/github.com/go-graphite/carbonapi/zipper/helper/requests.go:149\ngithub.com/go-graphite/carbonapi/zipper/protocols/v3.(*ClientProtoV3Group).Find\n\t/go/src/github.com/go-graphite/carbonapi/zipper/protocols/v3/protobuf_group.go:151\ngithub.com/go-graphite/carbonapi/zipper/protocols/v3.(*ClientProtoV3Group).ProbeTLDs\n\t/go/src/github.com/go-graphite/carbonapi/zipper/protocols/v3/protobuf_group.go:259\ngithub.com/go-graphite/carbonapi/zipper/broadcast.doProbe\n\t/go/src/github.com/go-graphite/carbonapi/zipper/broadcast/broadcast_group.go:611\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\n"}

[carbonapi.yaml](https://github.com/hnakamur/carbonapi-go-carbon-docker-compose-example/blob/cca566d738d7dc511f395a57af28e167c408cd90/carbonapi/carbonapi.yaml)

```
listen: "0.0.0.0:8081"
upstreams:
    backendsv2:
        backends:
          -
            groupName: "carbon"
            protocol: "carbonapi_v3_pb"
            lbMethod: "rr"
            maxTries: 3
            maxBatchSize: 0
            keepAliveInterval: "30s"
            concurrencyLimit: 1000
            maxIdleConnsPerHost: 1000
            timeouts:
                find: "10s"
                render: "50s"
                connect: "200ms"
            servers:
                - "http://go-carbon:8080"
logger:
    - logger: ""
      file: "stderr"
      level: "debug"
      encoding: "console"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
```

I looked into the source code.

[zipper/protocols/v3/protobuf_group.go#L63](https://github.com/go-graphite/carbonapi/blob/afe22176059846941e40e6fb52771d1a4f205092/zipper/protocols/v3/protobuf_group.go#L63)
`limiter` is created with groupName (`"carbon"` in the above `carbonapi.yaml` config) here.
```
	limiter := limiter.NewServerLimiter([]string{config.GroupName}, *config.ConcurrencyLimit)
```

[zipper/protocols/v3/protobuf_group.go#L82](https://github.com/go-graphite/carbonapi/blob/afe22176059846941e40e6fb52771d1a4f205092/zipper/protocols/v3/protobuf_group.go#L82)
And `httpQuery` is created with the same `limiter`.
```
	httpQuery := helper.NewHttpQuery(config.GroupName, config.Servers, *config.MaxTries, limiter, httpClient, httpHeaders.ContentTypeCarbonAPIv3PB)
```

[zipper/protocols/v3/protobuf_group.go#L151](https://github.com/go-graphite/carbonapi/blob/afe22176059846941e40e6fb52771d1a4f205092/zipper/protocols/v3/protobuf_group.go#L151)
When carbonapi calls go-carbon's `/metrics/find` API, it calls `DoQuery` method of `httpQuery`.
```
	res, err := c.httpQuery.DoQuery(ctx, logger, rewrite.RequestURI(), types.MultiGlobRequestV3{*request})
```

[zipper/helper/requests.go#L102](https://github.com/go-graphite/carbonapi/blob/afe22176059846941e40e6fb52771d1a4f205092/zipper/helper/requests.go#L102)
In `doRequest` method (which is called from `DoQuery` method), `httpQuery`  calls `c.limiter.Enter` with `server` (`"http://go-carbon:8080"` for the above config), not with `groupName` (`"carbon"` in the above config).
```
	err = c.limiter.Enter(ctx, server)
```

[limiter/limiter.go#L37-L49](https://github.com/go-graphite/carbonapi/blob/afe22176059846941e40e6fb52771d1a4f205092/limiter/limiter.go#L37-L49)
Because of this unmatch, `case sl.m[s] <- struct{}{}:` does not happen since `sl.m[s]` is `nil`, so `case <-ctx.Done():` happens and it causes `timeout exceeded` error. 
```
// Enter claims one of free slots or blocks until there is one.
func (sl RealLimiter) Enter(ctx context.Context, s string) error {
	if sl.m == nil {
		return nil
	}

	select {
	case sl.m[s] <- struct{}{}:
		return nil
	case <-ctx.Done():
		return errors.New("timeout exceeded")
	}
}
```

As a workaround, setting `concurrencyLimit` to `0` does not cause an `timeout exceeded` error.
