### ISSUE TITLE
carbonapi {"error":"unexpected EOF"}

### ISSUE THREAD

**Issue by cjagus** [go-graphite/carbonapi#455]
We started using 0.12.6 from .11 and noticing below erros on logs.

```
"type":"fetch","request":"&MultiFetchRequest{Metrics:[{host.snowflake-web.*.timers.snowflake.events.XXXX.load_lag.upper 1585244646 1585245546 false host.snowflake-web.*.timers.snowflake.events.XXXX.load_lag.upper []}],}","errors":[{"error":"unexpected EOF"}]}
```
We are using basic upstreams > backends: > go-carbon, in previous version we used to saw 404 errors in logs also noticed `sendGlobsAsIs` and `alwaysSendGlobsAsIs` is removed from the example configs 

cc @Civil

**Comment by Civil** [comment]
Since 0.11 there were a lot of changes in a way how carbonapi config is structured and in a way how to configure it. I would expect that the issue is in some configuration parameters that I by mistake not properly map from 0.11 to 0.12 format (carbonapi 0.12 internally convert old style config to a new style one, or at least tries to)

In 0.12, sendGlobsAsIs was mostly replaced with https://github.com/go-graphite/carbonapi/blob/master/doc/configuration.md#maxbatchsize and later with per-backend variant of the same option. For that option, 0 means unlimited and it should behave the same way as `alwaysSendGlobsAsIs: true` for 0.11, value of 1 should behave the same as `sendGlobsAsIs: false` and other value should behave as `sendGlobsAsIs: true` + `alwaysSendGlobsAsIs: false`.

Anyway, I have some follow up questions:
1. Could you please share the full config or at least specify what protocol you are using?
2. What previous version you've used?
3. In this case, do those metrics exist on the server?
4. Do you have relevant response from the go-carbon side? Potentially you can have a look at the result by using tcpdump.
5. What version of go-carbon are you using? With 0.12 I would recommend to use latest stable at least, as it could be that I've missed some corner case with older versions of go-carbon, however if I'll be able to replicate your issue I'll fix that as 0.12 should be able to work correctly with any version of go-carbon.

**Comment by cjagus** [comment]
> Could you please share the full config or at least specify what protocol you are using?
```
listen: "10.0.0.25:80"
concurency: 1000
cache:
   type: "mem"
   size_mb: 4096
   defaultTimeoutSec: 60

cpus: 0
tz: ""
sendGlobsAsIs: true
alwaysSendGlobsAsIs: false

functionsConfig:
    graphiteWeb: /etc/carbonapi/graphiteWeb.yaml
maxBatchSize: 1000

graphite:
    host: "10.0.0.25:2003"
    interval: "60s"
    prefix: "carbon.api"
    pattern: "{prefix}.{fqdn}"
idleConnections: 20
pidFile: ""

upstreams:
    buckets: 10
    timeouts:
        global: "60s"
        afterStarted: "60s"
        connect: "200ms"
    concurrencyLimit: 0
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100
    backends:
        - "http://graphite-1:8080"
        - "http://graphite-2:8080"
        - "http://graphite-3:8080"
        - "http://graphite-4:8080"
        - "http://graphite-5:8080"
        - "http://graphite-6:8080"
        - "http://graphite-7:8080"
        - "http://graphite-8:8080"
        - "http://graphite-9:8080"
        - "http://graphite-10:8080"
graphTemplates: /etc/carbonapi/graphTemplates.yaml
expireDelaySec: 10
#
logger:
    - logger: ""
      file: "/var/log/carbonapi/carbonapi.log"
      level: "error"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
      encoding: "json"
```
> What previous version you've used? 
0.11.0

> In this case, do those metrics exist on the server?
No metrics doesn't exist on the server

>Do you have relevant response from the go-carbon side? Potentially you can have a look at the result by using tcpdump.

I see 404 `"no metrics found","http_code":404}`

> What version of go-carbon are you using?  
 0.14.0

**Comment by Civil** [comment]
Ok, I think I have an idea what's going on and likely it's the same issue as described here with graphite-clickhouse: https://github.com/go-graphite/carbonapi/issues/454

But I'll try to reproduce it later today.

**Comment by cjagus** [comment]
@Civil Also noticed carbonapi[0.12.6 ] using high Memory [trying to use all the available memory in the instance] when trying to fetch metrics with lots of globs.

**Comment by Civil** [comment]
Can you share the heap profiler output?

To do that you need to enable pprof in the config (by default it's disabled)
```
# Specify if metrics are exported over HTTP and if they are available on the same address or not
# pprofEnabled controls if extra HTTP Handlers to profile and debug application will be available
expvar:
  enabled: true
  pprofEnabled: false
  listen: ""
```

`listen` directive there allows you to bind only on localhost for example and expose it on a different port. Currently all expvar stuff (including metrics) are controled by that listen directive, so if you change that - it will also change listener for the metircs and for pprof.

And after some of the heavy queries, please execute something like (assuming it's exposed on port 8081):
```
go tool pprof http://localhost:8081/debug/pprof/heap
```

And provide output of:
```
top10
```
top10 -cum
```
This one should produce svg image but it requires graphviz to be installed
```
web
```

As well as the logs of the carbonapi (I'm interested in what's in the logs) and if you can, please also share the current counters at carbonapi's url in `/debug/vars` (feel free to remove anything you don't want to share)
