### ISSUE TITLE
Different TLD behaviour in version 0.13.0

### ISSUE THREAD

**Issue by dorroddorrod** [go-graphite/carbonapi#484]
Hi,
We we are running carbonapi in production with version 0.12.5.

Today morning i've tried to upgrade carbonapi to version 0.13.0,
After the upgrade some of the requests didn't worked at all.

Tried to debug it a bit and looks like if we have 2 different graphite groups with the same TLD, it doesnt work at all.

This bug doesn't happen in version 0.12.5

My config file looks like that, when graphitelong-001 and graphitelong-005 sharing the same TLD
```
listen: "0.0.0.0:80"
prefix: ""
expvar:
  enabled: true
  pprofEnabled: false
  listen: ""
# Max concurrent requests to CarbonZipper
concurency: 1000
sendGlobsAsIs: false
cache:
   # Type of caching. Valid: "mem", "memcache", "null"
   type: "mem"
   # Cache limit in megabytes
   size_mb: 0
   # Default cache timeout value. Identical to DEFAULT_CACHE_DURATION in graphite-web.
   defaultTimeoutSec: 20
cpus: 0
# Timezone, default - local
tz: ""
maxBatchSize: 1000
graphite:
    host: "carbonrelay-new:2010"
    interval: "60s"
    prefix: "telemetry.carbon.api"
    pattern: "{prefix}.{fqdn}"
idleConnections: 10
pidFile: ""
upstreams:
    buckets: 10
    timeouts:
        find: "15s"
        render: "50s"
        connect: "50s"
    concurrencyLimitPerServer: 0
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100
    backendsv2:
        backends:

          -
            groupName: 'graphitelong-001'
            protocol: 'auto'
            lbMethod: 'all'
            maxTries: 3
            maxBatchSize: 0
            keepAliveInterval: '10s'
            concurrencyLimit: 0
            maxIdleConnsPerHost: 1000
            timeouts:
                find: '15s'
                render: '50s'
                connect: '200ms'
            servers:
                - "http://*****:8013"
                - "http://*****:8013"
                - "http://*****:8013"

          -
            groupName: 'graphitelong-003'
            protocol: 'auto'
            lbMethod: 'all'
            maxTries: 3
            maxBatchSize: 0
            keepAliveInterval: '10s'
            concurrencyLimit: 0
            maxIdleConnsPerHost: 1000
            timeouts:
                find: '15s'
                render: '50s'
                connect: '200ms'
            servers:
                - "http://*****:8013"
                - "http://*****:8013"
                - "http://*****:8013"

          -
            groupName: 'graphitelong-006'
            protocol: 'auto'
            lbMethod: 'all'
            maxTries: 3
            maxBatchSize: 0
            keepAliveInterval: '10s'
            concurrencyLimit: 0
            maxIdleConnsPerHost: 1000
            timeouts:
                find: '15s'
                render: '50s'
                connect: '200ms'
            servers:
                - "http://*****:8013"
                - "http://*****:8013"
                - "http://*****:8013"

          -
            groupName: 'graphitelong-005'
            protocol: 'auto'
            lbMethod: 'all'
            maxTries: 3
            maxBatchSize: 0
            keepAliveInterval: '10s'
            concurrencyLimit: 0
            maxIdleConnsPerHost: 1000
            timeouts:
                find: '15s'
                render: '50s'
                connect: '200ms'
            servers:
                - "http://*****:8013"
                - "http://*****:8013"
                - "http://*****:8013"

    graphite09compat: false
expireDelaySec: 10
logger:
    - logger: ""
      file: "/var/log/carbonapi/carbonapi.log"
      level: "info"
      encoding: "json"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
```
Please advice
