### ISSUE TITLE
upgrade from 0.10.0 to 0.14.0 (or main) behavior change when time series returns no results

### ISSUE THREAD

**Issue by joemiller** [go-graphite/carbonapi#506]
Ran into this issue when upgrading from 0.10.0 to 0.14.0. Tried the latest nightly build carbonapi_0.14.0-39+sha.g983afd_amd64.deb as well.

Backend is go-carbon 0.12.0 but also saw the issue when upgrading to 0.15.0, so I think this is a behavioral change in carbonapi.

Previously, when querying a metric that exists but has no metrics in the current time period the result would be http/200 with an image rendered with the red text `No Data`. Now, however, the result is a 500 and the text `no metrics in the Response`.

**Comment by deniszh** [comment]
Hi @joemiller ,

Could you please include carbonapi config file that you are using ?

**Comment by joemiller** [comment]
```yaml
# carbonapi config file

listen: "0.0.0.0:8080"
concurency: 50
cache:
   # Type of caching. Valid: "mem", "memcache", "null"
   type: "mem"
   size_mb: 1024
   defaultTimeoutSec: 60
cpus: 8
tz: ""
sendGlobsAsIs: false
maxBatchSize: 2000
graphite:
    # Host:port where to send internal metrics
    # Empty = disabled
    host: "graphite-ingest:2003"
    interval: "60s"
    prefix: "carbon.carbonapi"
    pattern: "{prefix}.{fqdn}"
idleConnections: 100
pidFile: ""
notFoundStatusCode: 200
# See https://github.com/go-graphite/carbonzipper/blob/master/example.conf#L70-L108 for format explanation
upstreams:
    buckets: 10

    timeouts:
        global: "300s"
        afterStarted: "120s"
        connect: "500ms"

    concurrencyLimit: 0
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100
    backends:
        - "http://go-carbon-0.go-carbon:8000"
        - "http://go-carbon-1.go-carbon:8000"
    graphite09compat: false
expireDelaySec: 10
logger:
    - logger: ""
      file: "stderr"
      encoding: "json"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
```

I thought perhaps the `notFoundStatusCode: 200` might help but it did not, and looking at the code that seems to apply only in the case of no matching metric name found, and not the case i'm seeing which is a metric exists but there were no data points within the requested interval. This is common in our setup with some of the statsd metrics due to our statsd configuration which does not keep state and send 0's for infrequently updated metrics.

I'm currently bisecting through the `deb` packages to find when this changed. I think it might be in 0.13.0. So far I have tested the `0.11.0-2-g4a6f7c` and `0.12.0-3-ga99c07` packages and the expected behavior of a 200 response with a `no data` image remains in both.
