### ISSUE TITLE
[BUG] receive two different metrics at the same time with almost the same query

### ISSUE THREAD

**Issue by Vlggg** [go-graphite/carbonapi#528]
Hello,
We use carbonapi-0.14.1 + carbon-clickhouse-0.11.1-1 + graphite-clickhouse-0.11.7 for gather metrics and monitor it with queries. For some reason, we see really strange things. Sometimes I see a new time point in the answer has value None. If I execute the same query at the same time but change the time period, I will see the time point has value.
Examples:
URL with query
```
http://graphite:9080/render?target=groupByTags(seriesByTag('name=k8s.kubernetes_deployment.replicas_available', 'datacenter=dc1', 'deployment_name=webui'), 'last', '')&from=-5min&until=-4min&format=json
```
response
```
[{u'tags': {u'datacenter': u'dc1', u'host': u'host1', u'namespace': u'prod', u'name': u'k8s.kubernetes_deployment.replicas_available', u'deployment_name': u'webui'}, u'target': u'k8s.kuberne
tes_deployment.replicas_available;=', u'datapoints': [[2, 1602365950], [2, 1602365960], [2, 1602365970], [2, 1602365980], [2, 1602365990], [2, 1602366000], [None, 1602366010]]}]
```
URL with almost the same query
```
http://graphite:9080/render?target=groupByTags(seriesByTag('name=k8s.kubernetes_deployment.replicas_available', 'datacenter=dc1', 'deployment_name=webui'), 'last', '')&from=-5min&until=-1min&format=json
```
response
```
[{u'tags': {u'datacenter': u'dc1', u'host': u'host1', u'namespace': u'prod', u'name': u'k8s.kubernetes_deployment.replicas_available', u'deployment_name': u'webui'}, u'target': u'k8s.kuberne
tes_deployment.replicas_available;=', u'datapoints': [[2, 1602365960], [2, 1602365970], [2, 1602365980], [2, 1602365990], [2, 1602366000], [2, 1602366010], [2, 1602366020], [2, 1602366030], [2, 1602366040], [2, 1602366050], [2, 1602366060
], [2, 1602366070], [2, 1602366080], [2, 1602366090], [2, 1602366100], [2, 1602366110], [2, 1602366120], [2, 1602366130], [2, 1602366140], [2, 1602366150], [2, 1602366160], [2, 1602366170], [2, 1602366180], [2, 1602366190]]}]
```

As you can see in the first query at 1602366010 value None but at the same time in the almost same query, I see value in place and equal 2.
difference in queries:
from=-5min&until=-4min

carbonapi config:
```
listen: "0.0.0.0:9080"

concurency: 20

cache:
   type: "null"
backendCache:
   type: "null"

cpus: 0

tz: ""

sendGlobsAsIs: true

alwaysSendGlobsAsIs: true

#functionsConfigs:
#    graphiteWeb: ./graphiteWeb.yaml

maxBatchSize: 100000


graphite:
    host: ""
    interval: "60s"
    prefix: "collectd"
    pattern: "{prefix}.{host}"

idleConnections: 10

pidFile: "/var/run/carbonapi.pid"

upstreams:
    buckets: 10
    timeouts:
        global: "10s"
        afterStarted: "2s"
        connect: "200ms"
    concurrencyLimit: 0
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100

    backends:
        - "http://localhost:9090"
    graphite09compat: false

#graphTemplates: /etc/carbonapi/graphTemplates.yaml

expireDelaySec: 10

logger:
    - logger: ""
      file: "/var/log/carbonapi/carbonapi_error.log"
      level: "debug"
      encoding: "json"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
    - logger: ""
      file: "/var/log/carbonapi/carbonapi.log"
      level: "info"
      encoding: "json"
```

**Question**
Could you please help me understand why it's happening? Is this bug or a bad configuration of one of the parts?
