### ISSUE TITLE
Cache of unavailable metrics

### ISSUE THREAD

**Issue by radinv** [go-graphite/carbonapi#547]
**Problem description**
I have 2 go-carbon clusters in different DCs. To see metrics from applications from different DCs in one Grafana dashboard, I added carbonapi in the second DC as a backend to carbonapi in the first DC. Since in carbonapi lbMethod: "broadcast" go-carbon from the second DC accepts a lot of requests from the first DC and cannot find metrics, since they are not there.

**carbonapi's version**
0.14.1

**carbonapi's config from first DC**
```
listen: "0.0.0.0:8081"
concurency: 30
cpus: 0
tz: ""
functionsConfig:
    graphiteWeb: /etc/carbonapi/graphiteWeb.yaml
maxBatchSize: 300
graphite:
    host: ""
    interval: "60s"
    prefix: "carbon.api"
    pattern: "{prefix}.{fqdn}"
idleConnections: 10
pidFile: "/var/run/carbonapi/carbonapi.pid"
upstreams:
    buckets: 10
    timeouts:
        find: "2s"
        render: "10s"
        connect: "200ms"
    concurrencyLimitPerServer: 0
    keepAliveInterval: "30s"
   maxIdleConnsPerHost: 100
    backends:
        - "http://10.0.1.131:8080"
        - "http://10.0.1.132:8080"
        - "http://10.0.1.133:8080"
        - "https://carbonapi.cloud.cian.tech"
    backendsv2:
        backends:
          -
            groupName: "group1"
            #
            protocol: "carbonapi_v2_pb"
            lbMethod: "broadcast"
            maxTries: 3
            maxGlobs: 100
            keepAliveInterval: "10s"
            concurrencyLimit: 0
            maxIdleConnsPerHost: 1000
            timeouts:
                find: "2s"
                render: "50s"
                connect: "200ms"
            servers:
                - "http://127.0.0.2:8080"
                - "http://127.0.0.3:8080"
          -
            groupName: "group2"
            protocol: "carbonapi_v3_pb"
            lbMethod: "roundrobin"
            servers:
                - "http://127.0.0.4:8080"
                - "http://127.0.0.5:8080"
    graphite09compat: true
graphTemplates: /etc/carbonapi/graphTemplates.yaml
expireDelaySec: 10
defaultColors:
      "red": "ff0000"
      "green": "00ff00"
      "blue": "#0000ff"
      "darkred": "#c80032"
      "darkgreen": "00c800"
      "darkblue": "002173"
logger:
    - logger: ""
      file: "/var/log/carbonapi.log"
      level: "warn"
      encoding: "json"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
```

**carbonapi's config from second DC**
```
listen: "0.0.0.0:8081"
concurency: 1000
cpus: 0
tz: ""
maxBatchSize: 300
graphite:
    host: ""
    interval: "60s"
    prefix: "carbon.api"
    pattern: "{prefix}.{fqdn}"
idleConnections: 10
pidFile: "/var/run/carbonapi/carbonapi.pid"
upstreams:
    buckets: 10
    timeouts:
        find: "2s"
        render: "10s"
        connect: "200ms"
    concurrencyLimitPerServer: 0
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100
    backendsv2:
        backends:
          -
            groupName: "go-carbon"
            protocol: "carbonapi_v3_pb"
            lbMethod: "broadcast"
            maxTries: 3
            maxGlobs: 100
            keepAliveInterval: "10s"
            concurrencyLimit: 0
            maxIdleConnsPerHost: 1000
            timeouts:
                find: "2s"
                render: "50s"
                connect: "200ms"
            servers:
                - "http://go-carbon-0.go-carbon.monitoring.svc.cluster.local:8080"
                - "http://go-carbon-1.go-carbon.monitoring.svc.cluster.local:8080"
                - "http://go-carbon-2.go-carbon.monitoring.svc.cluster.local:8080"
    graphite09compat: true
expireDelaySec: 10
defaultColors:
      "red": "ff0000"
      "green": "00ff00"
      "blue": "#0000ff"
      "darkred": "#c80032"
      "darkgreen": "00c800"
      "darkblue": "002173"
logger:
    - logger: "slow"
      file: "stdout"
      level: "warn"
      encoding: "json"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
```
go-carbon in first DC
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/55874175/102468075-1fd5a580-4062-11eb-9a24-7e89a94bcb11.png">

go-carbon in second DC
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/55874175/102468154-3b40b080-4062-11eb-80ba-60f1286a9773.png">

**Question:** is there a setting in carbonapi that will allow you not to search every time for a metric that is not there? can it cache the response?
