### ISSUE TITLE
Working with 2 go-carbon clusters

### ISSUE THREAD

**Issue by radinv** [go-graphite/carbonapi#557]
**Problem description**
I have 2 graphite cluster. Application send metric to first cluster, but now it sending in second cluster.
Metric path identity in 2 cluster. I have trouble, when carbonapi sending get to all clusters. I have first answer from random cluster. I tried configured backendsv2 with 2 groups, but it not working... How i can fix my problem? 

**carbonapi's version**
0.10.0.1

**carbonapi's config**
```
listen: "0.0.0.0:8081"
concurency: 30
cpus: 0
tz: ""
functionsConfig:
    graphiteWeb: /etc/carbonapi/graphiteWeb.yaml
maxBatchSize: 300
graphite:
    host: ""
    interval: "60s"
    prefix: "carbon.api"

    pattern: "{prefix}.{fqdn}"
idleConnections: 10
pidFile: "/var/run/carbonapi/carbonapi.pid"
upstreams:
    buckets: 10
    timeouts:
        find: "2s"
        render: "10s"
        connect: "200ms"
    concurrencyLimitPerServer: 0
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100
    backends:
        - "http://10.0.1.131:8080"
        - "http://10.0.1.132:8080"
        - "http://10.0.1.133:8080"
        - "https://carbonapi.second"
    graphite09compat: true
graphTemplates: /etc/carbonapi/graphTemplates.yaml
expireDelaySec: 10
defaultColors:
      "red": "ff0000"
      "green": "00ff00"
      "blue": 
      "darkred": 
      "darkgreen": "00c800"
      "darkblue": "002173"
logger:
    - logger: ""
      file: "/var/log/carbonapi.log"
      level: "warn"
      encoding: "json"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
```

I tried this config:
```
    backendsv2:
        backends:
          -
            groupName: "group1"
            protocol: "carbonapi_v2_pb"
            lbMethod: "broadcast"
            servers:
                - "http://10.0.1.131:8080"
                - "http://10.0.1.132:8080"
                - "http://10.0.1.133:8080"
          -
            groupName: "group2"
            protocol: "carbonapi_v2_pb"
            lbMethod: "broadcast"
            servers:
                - "https://carbonapi.second"
```

**Comment by Civil** [comment]
0.10.0.1 is a very old release (almost 3 years old). To be honest, even if it had a bug, I don't have time to figure out what was wrong there and to fix it (also as far as I remember, 0.10.0.1 doesn't have a support for multiple backends and different protocols, that's something that happened in 0.11 and since then was polished a lot).

So my suggestion would be to start with upgrade to latest stable release or latest master, that might require some config changes, as even though I've tried to keep changelog in a meaningful state, I might've missed something.

**Comment by radinv** [comment]
I'm update carbonapi and it work!
But now i have next problem. Request to carbonapi with "*" have response 500.
Image for example:
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/55874175/105723157-84283680-5f37-11eb-9412-0bfd5a1c3065.png">
But if i select corrent metric it is good.
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/55874175/105723241-9dc97e00-5f37-11eb-8517-fc21207fc303.png">

**Comment by radinv** [comment]
in carbonapi.log
```
{"level":"WARN","timestamp":"2021-01-25T18:13:50.345+0300","logger":"zipper","message":"find request failed when resolving globs","type":"broadcastGroup","groupName":"root","metric_name":"stats.test.group1.*","error":"metric not found"}
{"level":"ERROR","timestamp":"2021-01-25T18:13:50.346+0300","logger":"access","message":"request failed","data":{"handler":"render","carbonapi_uuid":"82783bdc-0fe3-4221-ad47-46396ac917f7","url":"/render","peer_ip":"10.0.0.122","host":"10.0.1.133:8081","format":"json","use_cache":true,"targets":["stats.test.group1.*"],"cache_timeout":60,"runtime":0.070822667,"http_code":500,"reason":"error or no response: no metrics in the Response","from":1611585830,"until":1611587630,"from_raw":"-30min","until_raw":"now","uri":"/render","from_cache":false,"used_backend_cache":false,"request_headers":{}}}
```

**Comment by Civil** [comment]
And what's the current config that you are using?

**Comment by radinv** [comment]
carbonapi.yaml
```
listen: "0.0.0.0:8081"
concurency: 30
cpus: 0
tz: ""

functionsConfig:
    graphiteWeb: /etc/carbonapi/graphiteWeb.yaml
maxBatchSize: 300
graphite:
    host: ""
    interval: "60s"
    prefix: "carbon.api"
    pattern: "{prefix}.{fqdn}"
idleConnections: 10
pidFile: "/var/run/carbonapi/carbonapi.pid"
upstreams:
    buckets: 10

    timeouts:
        find: "2s"
        render: "10s"
        connect: "200ms"

    concurrencyLimitPerServer: 0

    keepAliveInterval: "30s"

    maxIdleConnsPerHost: 100

    backendsv2:
        backends:
          -
            groupName: "group1"
            protocol: "carbonapi_v2_pb"
            lbMethod: "broadcast"
            keepAliveInterval: "10s"
            timeouts:
                find: "2s"
                render: "50s"
                connect: "200ms"
            servers:
                - "http://10.0.1.131:8080"
                - "http://10.0.1.132:8080"
                - "http://10.0.1.133:8080"
          -
            groupName: "group2"
            protocol: "carbonapi_v2_pb"
            lbMethod: "broadcast"
            timeouts:
                find: "2s"
                render: "50s"
                connect: "200ms"
            keepAliveInterval: "10s"
            servers:
                - "https://carbonapi.second"
               

    graphite09compat: true
graphTemplates: /etc/carbonapi/graphTemplates.yaml
expireDelaySec: 10
defaultColors:
      "red": "ff0000"
      "green": "00ff00"
      "blue": "#0000ff"
      "darkred": "#c80032"
      "darkgreen": "00c800"
      "darkblue": "002173"
logger:
    - logger: ""
      file: "/var/log/carbonapi.log"
      level: "warn"
      encoding: "json"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
```
