### ISSUE TITLE
[BUG] upstream buckets setting not honored

### ISSUE THREAD

**Issue by obfuscurity** [go-graphite/carbonapi#558]
**Describe the bug**
The buckets setting for upstreams does not appear to be honored. Based on my understanding from reading the docs and the source code, setting this value higher than 10 should increase the number of 100ms request duration histogram buckets while also changing the threshold for "Slow Request" logged events.

We've tried changing this setting to 300 to accommodate some very large queries, giving us more visibility up to 30s duration and also decreasing our logging traffic. Unfortunately, we continue to only see 100ms buckets up to 1000ms and logged requests for anything longer than 1s.

**CarbonAPI Version**
We're currently stuck on 0.12.6 due to other bugs present in the current stable release. Reading the source code, I see nothing to suggest this issue is fixed in HEAD.

**Logs**
```
Jan 28 19:48:17 XXX carbonapi[513368]: {"level":"WARN","timestamp":"2021-01-28T19:48:17.901Z","logger":"slow","message":"Slow Request","time":1.95341171,"url":"/render","referer":""}
```

**CarbonAPI Configuration:**
```
listen: "127.0.0.1:8082"
pidFile: "/var/run/carbonapi/carbonapi.pid"
concurency: 1000
cpus: 0
tz: "UTC,0"

expireDelaySec: 0

cache:
   type: "mem"
   size_mb: 0
   defaultTimeoutSec: 60

graphite:
    host: "127.0.0.1:2003"
    interval: "60s"
    prefix: "carbon.api"

upstreams:
    graphite09compat: false
    buckets: 3000
    concurrencyLimitPerServer: 0
    maxIdleConnsPerHost: 100
    keepAliveInterval: "30s"

    timeouts:
        find: "5s"
        render: "60s"
        connect: "200ms"

    carbonsearchv2:
        prefix: "virt.v1.*"
        backends:
            -
                groupName: "disabled"
                protocol: "carbonapi_v2_pb"
                lbMethod: "rr"
                servers:
                    - ""
    backendsv2:
        backends:
            -
                groupName: "go-carbon-localhost"
                protocol: "carbonapi_v3_pb"
                lbMethod: "rr"
                maxTries: 3
                maxBatchSize: 100
                concurrencyLimit: 0
                servers:
                    - "http://127.0.0.1:8080"

unicodeRangeTables:
    - "Latin"
    - "Hiragana"
    - "Katakana"
    - "Han"

logger:
    - logger: ""
      file: "stderr"
      level: "warn"
      encoding: "json"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
```

**Simplified query (if applicable)**
We don't have a single query that's representative of the issue. It's not specific to any particular render functions.

**Backend metric retention and aggregation schemas**
Not applicable.

**Backend response (if possible)**
Not applicable.

**Additional context**
None.
