### ISSUE TITLE
[General] Parsing Error Whenever Using Functions

### ISSUE THREAD

**Issue by cthiel42** [go-graphite/carbonapi#583]
**Problem Description**
I get a parsing error whenever I attempt to use a query with a function in it. All of my queries with functions work when done through graphite-web, but not through carbonapi. I was wondering if you've ever seen this before. I was originally using v0.14.1, but even after updating to v0.15.2 I still have the problem, which makes me think I'm either making a configuration mistake or an installation mistake. For reference I'm using Go version 1.15.7.

An example of a query that causes the error is:
`/render/?from=-5minutes&target=scale(foo.*.prd.*.CpuUtilization.value,1000)`

The response I get from the query is:
````
Bad Request: Bad Request

Target              : scale(foo.*.prd.*.CpuUtilization.value,1000)
Parsed so far       : scale(foo.*.prd.*.CpuUtilization.value
Could not parse     : ,1000)
````

A log from the request in carbonapi looks like this:
````
ERROR	access	request failed	
{"data": {
    "handler":"render",
    "carbonapi_uuid":"----",
    "url":"/render/?from=-5minutes&target=scale(foo.*.prd.*.CpuUtilization.value,1000)",
    "peer_ip":"----",
    "host":"----",
    "use_cache":true,
    "targets":["scale(foo.*.prd.*.CpuUtilization.value,1000)"],
    "cache_timeout":60,
    "runtime":0.000139551,
    "http_code":400,
    "reason":"Bad Request\n\nTarget              : scale(foo.*.prd.*.CpuUtilization.value,1000)\nParsed so far       : scale(foo.*.prd.*.CpuUtilization.value\nCould not parse     : ,1000)\n",
    "from":1615602485,
    "until":1615602785,
    "from_raw":"-5minutes",
    "uri":"/render/?from=-5minutes&target=scale(foo.*.prd.*.CpuUtilization.value,1000)",
    "from_cache":false,
    "used_backend_cache":false,
    "request_headers":{}
    }
}
````

**Configuration**
````yaml
listen: "x.x.x.x:8081"

prefix: ""

unicodeRangeTables:
  - "all"

cache:
  type: "mem"
  size_mb: 0
  defaultTimeoutSec: 60

backendCache:
  type: "mem"
  size_mb: 0
  defaultTimeoutSec: 60

cpus: 2

graphite:
    host: "localhost:2003"
    interval: "60s"
    prefix: "carbon.carbonapi"

upstreams:
    graphite09compat: false
    buckets: 10

    concurrencyLimitPerServer: 0
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 1000
    timeouts:
        find: "4s"
        render: "30s"
        connect: "500ms"

    backendsv2:
        backends:
          -
            groupName: "go-carbon-group1"
            protocol: "carbonapi_v3_pb"
            lbMethod: "broadcast"
            maxTries: 3
            maxBatchSize: 1000
            keepAliveInterval: "30s"
            concurrencyLimit: 0
            maxIdleConnsPerHost: 1000
            timeouts:
                find: "4s"
                render: "30s"
                connect: "500ms"
            servers:
                - "http://127.0.0.1:8080"
````

Let me know if there's anything you notice I'm doing incorrectly, or want any more information.
