### ISSUE TITLE
[BUG] Unicode RangeTable 'Common' breaks functions 

### ISSUE THREAD

**Issue by adamcstephens** [go-graphite/carbonapi#598]
**Describe the bug**
Adding the unicode range `Common`, or using `all` which includes Common, causes functions to fail. and return a 400. I was attempting to add this table since it includes the En Dash character.

**CarbonAPI Version**
Tested on 0.14.0 and 0.15.2

**Logs**

`Apr 14 17:13:07 graphite01 carbonapi[18629]: {"level":"ERROR","timestamp":"2021-04-14T17:13:07.895Z","logger":"access","message":"request failed","data":{"handler":"render","carbonapi_uuid":"2dc60e01-3445-4f92-a11d-f5a393da968f","url":"/render","peer_ip":"1.1.1.1","host":"localhost:8082","format":"json","use_cache":true,"targets":["aliasByNode(test.*.*.5xx, 1)"],"cache_timeout":60,"runtime":0.000340074,"http_code":400,"reason":"Bad Request\n\nTarget              : aliasByNode(test.*.*.5xx, 1)\nParsed so far       : aliasByNode(test.*.*.5xx\nCould not parse     : , 1)\n","from":1618416787,"until":1618420387,"from_raw":"-1h","until_raw":"now","uri":"/render","from_cache":false,"request_headers":{}}}`

**CarbonAPI Configuration:**

```
listen: "127.0.0.1:8082"
pidFile: "/var/run/carbonapi/carbonapi.pid"
concurency: 1000
cpus: 0
tz: "UTC,0"

expireDelaySec: 0

cache:
   type: "mem"
   size_mb: 0
   defaultTimeoutSec: 60

graphite:
    host: "127.0.0.1:2003"
    interval: "60s"
    prefix: "carbon.api"

upstreams:
    graphite09compat: false
    buckets: 10
    concurrencyLimitPerServer: 0
    maxIdleConnsPerHost: 100
    keepAliveInterval: "30s"

    timeouts:
        find: "5s"
        render: "60s"
        connect: "200ms"

    carbonsearchv2:
        prefix: "virt.v1.*"
        backends:
            -
                groupName: "disabled"
                protocol: "carbonapi_v2_pb"
                lbMethod: "rr"
                servers:
                    - ""
    backendsv2:
        backends:
            -
                groupName: "go-carbon-localhost"
                protocol: "carbonapi_v3_pb"
                lbMethod: "rr"
                maxTries: 3
                maxBatchSize: 100
                concurrencyLimit: 0
                servers:
                    - "http://127.0.0.1:8080"

unicodeRangeTables:
    - "Latin"
    - "Common"

logger:
    - logger: ""
      file: "stderr"
      level: "warn"
      encoding: "json"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
```
**Simplified query (if applicable)**
Query: `aliasByNode(test.*.*.5xx, 1)`

Test Data:
```
test.first.site1.5xx 892 1618421007
test.first.site2.5xx 968 1618421007
test.third.site2.5xx 219 1618421007
test.second.site2.5xx 2923 1618421007
test.second.site1.5xx 2839 1618421007
test.third.site1.5xx 203 1618421007
```

**Backend metric retention and aggregation schemas**

```
graphite01:~$ cat /etc/go-carbon/storage-schemas.conf
[01.carbon]
pattern = ^carbon\.
retentions = 60s:15d,5m:180d

[03.metric_testing]
pattern = ^metric_testing
retentions = 60s:1d,5m:7d

[04.grafana]
pattern = ^grafana\.
retentions = 60s:15d

[99.default_1min_for_90day]
pattern = .*
retentions = 60s:15d,5m:180d

graphite01:~$ cat /etc/go-carbon/storage-aggregation.conf
[default]
pattern = .*
xFilesFactor = 0.5
aggregationMethod = average
```

**Backend response (if possible)**
here's a find of these metrics.

```
graphite01:~$ curl -s 'localhost:8080/metrics/find/?query=test.*.*.5xx' | jq .
{
  "metrics": [
    {
      "name": "test.*.*.5xx",
      "matches": [
        {
          "path": "test.first.site1.5xx",
          "isLeaf": true
        },
        {
          "path": "test.first.site2.5xx",
          "isLeaf": true
        },
        {
          "path": "test.second.site1.5xx",
          "isLeaf": true
        },
        {
          "path": "test.second.site2.5xx",
          "isLeaf": true
        },
        {
          "path": "test.third.site1.5xx",
          "isLeaf": true
        },
        {
          "path": "test.third.site2.5xx",
          "isLeaf": true
        }
      ]
    }
  ]
```

**Additional context**
Tested with go-carbon 0.14.0 and 0.15.3
