### ISSUE TITLE
[BUG]  Enable cairo/png support by default in the Docker image

### ISSUE THREAD

**Issue by travis-bear** [go-graphite/carbonapi#606]
**Describe the bug**
Currently the docker image for carbonapi is built with cairo/png support explicitly disabled.

**CarbonAPI Version**
Docker image `gographite/carbonapi:v0.15.1`

**CarbonAPI Configuration:**
```
listen: "0.0.0.0:8081"

# Specify URL Prefix for all handlers
prefix: ""

# Specify if metrics are exported over HTTP and if they are available on the same address or not
# pprofEnabled controls if extra HTTP Handlers to profile and debug application will be available
expvar:
  enabled: true
  pprofEnabled: false
  listen: ""

# Controls headers that would be passed to the backend
headersToPass:
  - "X-Dashboard-Id"
  - "X-Grafana-Org-Id"
  - "X-Panel-Id"
headersToLog:
  - "X-Dashboard-Id"
  - "X-Grafana-Org-Id"
  - "X-Panel-Id"
# Specify custom function aliases.
# This is example for alias "perMinute(metrics)" that will behave as "perSecond(metric)|scale(60)"
define:
  - name: "perMinute"
    template: "perSecond({{.argString}})|scale(60)"
# Control what status code will be returned where /render or find query do not return any metric. Default is 200
notFoundStatusCode: 200

# Max concurrent requests to CarbonZipper
concurency: 1000
cache:
  # Type of caching. Valid: "mem", "memcache", "null"
  type: "mem"
  # Cache limit in megabytes
  size_mb: 0
  # Default cache timeout value. Identical to DEFAULT_CACHE_DURATION in graphite-web.
  defaultTimeoutSec: 60
  # Only used by memcache type of cache. List of memcache servers.
#   memcachedServers:
#       - "127.0.0.1:1234"
#       - "127.0.0.2:1235"
# Amount of CPUs to use. 0 - unlimited
cpus: 0

maxBatchSize: 100
graphite:
  host: "relay-graph.<...>:2003"
  interval: "60s"
  prefix: "carbon.api"
idleConnections: 10
pidFile: ""

upstreams:
  tldCacheDisabled: false
  buckets: 10
  slowLogThreshold: "3s"
  timeouts:
    find: "4s"
    render: "15s"
    connect: "600ms"

  concurrencyLimitPerServer: 0
  keepAliveInterval: "30s"
  maxIdleConnsPerHost: 100
  doMultipleRequestsIfSplit: false

  backendsv2:
    backends:
      - groupName: "victoriametrics"
        protocol: "victoriametrics"
        lbMethod: "broadcast"
        maxTries: 3
        maxBatchSize: 0
        keepAliveInterval: "10s"
        concurrencyLimit: 0
        maxIdleConnsPerHost: 1000
        backendOptions:
          step: "60"
          start: "-5m"
          max_points_per_query: 5000
          probe_version_interval: "600s"
          fallback_version: "v0.0.0"
        timeouts:
          find: "2s"
          render: "50s"
          connect: "200ms"
        servers:
          - "http://<...>01:8428"
          - "http://<...>02:8428"


  graphite09compat: false

expireDelaySec: 10

logger:
  - logger: ""
    file: "/var/log/app/gcapi/carbonapi.log"
    level: "info"
    encoding: "console"
```

**Simplified query (if applicable)**
Data is successfully returned when request is for `json` format
http://gcapi.service.consul:8081/render/?width=600&height=300&target=1m.prod.gl.a.aie.bgram.brw1.prod-gl-a-aie-bgram-brw1-86579d4d94-pd8fr.riemann-stats.riemann_netty_event-executor_queue_size&format=json

Zero-length/empty response is returned  when request is for `png` format
http://gcapi.service.consul:8081/render/?width=600&height=300&target=1m.prod.gl.a.aie.bgram.brw1.prod-gl-a-aie-bgram-brw1-86579d4d94-pd8fr.riemann-stats.riemann_netty_event-executor_queue_size&format=png

**Additional context**
VictoriaMetrics backend
