### ISSUE TITLE
[BUG] prometheus_group doesn't use maxDataPoints param for request when using VictoriaMetrics

### ISSUE THREAD

**Issue by limpasha** [go-graphite/carbonapi#607]
**Describe the bug**
When querying

```
curl '0:8081/render?target=pulse.test_sum&format=csv&from=-10d&until=now&maxDataPoints=1000000'
```
calculating of step doesn't use providedd maxDataPoints. 

**CarbonAPI Version**
4eb7c0357c02db44c4a161a256fc56989030f93d

**Logs**
```sh
% curl '0:8081/render?target=pulse.test_sum&format=csv&from=-10d&until=now&maxDataPoints=1000000' -s | head -3
"pulse.test_sum",2021-05-11 15:55:00,2
"pulse.test_sum",2021-05-11 15:56:00,
"pulse.test_sum",2021-05-11 15:57:00,100
```
so the step is derived as `120s`, which is `864000 (10d) / 11000 (default hardcoded maxPointsPerQuery)`

**CarbonAPI Configuration:**
```yaml
listen: "0.0.0.0:8081"
concurency: 20
cpus: 10
tz: ""
sendGlobsAsIs: true
maxBatchSize: 1000000
cache:
    type: "null"
idleConnections: 10
pidFile: ""
upstreams:
    buckets: 10
    timeouts:
        global: "60s"
        afterStarted: "10s"
        connect: "200ms"
    concurrencyLimit: 10
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100
    tldCacheDisabled: true
    backends:
    backendsv2:
        backends:
          - groupName: "victoria"
            protocol: "victoriametrics"
            lbMethod: "broadcast"
            backendOptions:
                step: "60"
            servers:
                - "http://dev:5000"
expireDelaySec: 10
```
