### ISSUE TITLE
[BUG] Consolidation is perfomed before function is evaluated resulting in wrong aggregated results

### ISSUE THREAD

**Issue by limpasha** [go-graphite/carbonapi#611]
**Describe the bug**
When querying for data for a long period with any aggregating function (like summarize, for example), incorrect result are returned, which is unexpected and so this types of queries seems unreliable. As far as I understand the root cause of the problem is adjusting `step` according to `maxDataPoints`.

**Detailed explanation**
Imagine the query `target=summarize(pulse.test_sum, "1d", "sum", false)&from=-10d&until=now&maxDataPoints=100`. The right way to do it correctly is to
- fetch **all** data points from storage
- compute 10 sums, which results in 10 points (10 days, summarize by 1 day)

**So**, what carbonapi does here https://github.com/go-graphite/carbonapi/blob/bb33f26c8466deb9c9134c1085d6fcf77cc02205/cmd/carbonapi/http/render_handler.go#L268
- fetches datapoints https://github.com/go-graphite/carbonapi/blob/bb33f26c8466deb9c9134c1085d6fcf77cc02205/expr/expr.go#L69
- inside the function above `step` **is adjusted according to** `maxDataPoints` provided param, that's why not all metrics are returned from backend https://github.com/go-graphite/carbonapi/blob/bb33f26c8466deb9c9134c1085d6fcf77cc02205/zipper/protocols/prometheus/prometheus_group.go#L236
- then this **incomplete data is used in aggregation** https://github.com/go-graphite/carbonapi/blob/bb33f26c8466deb9c9134c1085d6fcf77cc02205/expr/expr.go#L100

**CarbonAPI Version**
bb33f26c8466deb9c9134c1085d6fcf77cc02205

**Logs**
1. Data we have prepared (show only non-null), maxDataPoints= 10days * 60s step:
```
 % curl '0:8081/render?target=pulse.test1_sum&format=csv&from=-10d&until=now&maxDataPoints=14400' -s | egrep -v ',$'"pulse.test1_sum",2021-05-08 14:19:00,1
"pulse.test1_sum",2021-05-08 14:20:00,1
"pulse.test1_sum",2021-05-08 14:21:00,1
"pulse.test1_sum",2021-05-09 14:19:00,1
"pulse.test1_sum",2021-05-09 14:20:00,1
"pulse.test1_sum",2021-05-09 14:21:00,1
"pulse.test1_sum",2021-05-09 14:22:00,1
"pulse.test1_sum",2021-05-09 14:23:00,1
"pulse.test1_sum",2021-05-10 14:19:00,1
"pulse.test1_sum",2021-05-11 14:20:00,1
"pulse.test1_sum",2021-05-11 14:21:00,1
"pulse.test1_sum",2021-05-12 14:20:00,1
"pulse.test1_sum",2021-05-12 14:21:00,1
"pulse.test1_sum",2021-05-12 14:22:00,1
"pulse.test1_sum",2021-05-12 14:23:00,1
"pulse.test1_sum",2021-05-12 14:24:00,1
"pulse.test1_sum",2021-05-12 14:25:00,1
"pulse.test1_sum",2021-05-12 14:26:00,1
"pulse.test1_sum",2021-05-12 14:27:00,1
"pulse.test1_sum",2021-05-12 14:28:00,1
```
2. Then try `summarize` with **enough** datapoints (_correct_):
```
% curl '0:8081/render?target=summarize(pulse.test1_sum,"1d","sum",false)&format=csv&from=-10d&until=now&maxDataPoints=14400' -s | egrep -v ',$'
"summarize(pulse.test1_sum,'1d','sum',false)",2021-05-08 00:00:00,3
"summarize(pulse.test1_sum,'1d','sum',false)",2021-05-09 00:00:00,5
"summarize(pulse.test1_sum,'1d','sum',false)",2021-05-10 00:00:00,1
"summarize(pulse.test1_sum,'1d','sum',false)",2021-05-11 00:00:00,2
"summarize(pulse.test1_sum,'1d','sum',false)",2021-05-12 00:00:00,9
```
3. Then try `summarize` with **NOT enough** datapoints (_incorrect_):
```
% curl '0:8081/render?target=summarize(pulse.test1_sum,"1d","sum",false)&format=csv&from=-10d&until=now&maxDataPoints=1440' -s | egrep -v ',$' 
"summarize(pulse.test1_sum,'1d','sum',false)",2021-05-08 00:00:00,1
"summarize(pulse.test1_sum,'1d','sum',false)",2021-05-09 00:00:00,1
"summarize(pulse.test1_sum,'1d','sum',false)",2021-05-11 00:00:00,1
"summarize(pulse.test1_sum,'1d','sum',false)",2021-05-12 00:00:00,1
```

**PS**

As far as I have dived into the problem deeply, I thinks I would be able to make PR fixing it. My idea is to have at least some configuration flag which forces using minimal `step` when fetching data. What do you guys think about it?

**CarbonAPI Configuration:**
```
listen: "0.0.0.0:8081"
concurency: 20
cpus: 10
tz: ""
sendGlobsAsIs: true
maxBatchSize: 1000000
cache:
    type: "null"
idleConnections: 10
pidFile: ""
upstreams:
    buckets: 10
    timeouts:
        global: "60s"
        afterStarted: "10s"
        connect: "200ms"
    concurrencyLimit: 10
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100
    tldCacheDisabled: true
    backends:
    backendsv2:
        backends:
          - groupName: "victoria"
            protocol: "victoriametrics"
            lbMethod: "broadcast"
            backendOptions:
                step: "60"
            servers:
                - "http://dev:5000"
expireDelaySec: 10
```
