### ISSUE TITLE
[BUG] victoriametrics version detection fails for vm cluster

### ISSUE THREAD

**Issue by ikod** [go-graphite/carbonapi#621]
**Describe the bug**

carbonapi detects VM version quering 'metrics' url formed from the backend servers base url just appending '/metrics'. This works both for single node and cluster version, as VM supports url http://vmnode/metrics for both cluster and single-node. See https://github.com/go-graphite/carbonapi/blob/main/zipper/protocols/victoriametrics/feature_set.go#L149

For `query_range` cluster VM require `AccountID` in request url: http://vmnode/select/0/prometheus/query_range... so 
base url in `backends` must include this `/select/0/prometheus` part. But clustered VM do not support `metrics` request like http://vmnode/select/0/prometheus/metrics - which carbonapi will use to detect VM version.

_So the problem is: when working with clustered VM, carbonapi can either detect VM version, or make timeseries queries, not both._

**CarbonAPI Version**

v0.15.4

**Logs**
```
2021-06-14T07:20:38.775Z        DEBUG   zipper  got slot for server     {"type": "victoriametrics", "protocol": "victoriametrics", "name": "victoriametrics", "function": "updateFeatureSet", "function": "HttpQuery.doRequest", "server": "http://vmselect-cluster.internal/select/0/prometheus", "name": "victoriametrics", "uri": "http://vmselect-cluster.internal/select/0/prometheus/metrics", "name": "http://vmselect-cluster.internal/select/0/prometheus"}

2021-06-14T07:20:38.791Z        DEBUG   zipper  have errors     {"type": "victoriametrics", "protocol": "victoriametrics", "name": "victoriametrics", "function": "updateFeatureSet", "error": "remoteAddr: \"10.56.4.82:50354\", X-Forwarded-For: \"10.253.130.19\"; unsupported path requested: \"/select/0/prometheus/metrics\"\n", "errorVerbose": "remoteAddr: \"10.56.4.82:50354\", X-Forwarded-For: \"10.253.130.19\"; unsupported path requested: \"/select/0/prometheus/metrics\"\n\nHTTP Code: 400\n\ngithub.com/go-graphite/carbonapi/zipper/types.init\n\t/root/go/src/github.com/go-graphite/carbonapi/zipper/types/errors.go:27\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6309\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6286\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6286\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6286\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:208\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\n"}
```

**CarbonAPI Configuration:**

```yaml
   backendsv2:                                                                                                                                                                                 backends:
          -
            groupName: "victoriametrics"
            protocol: "victoriametrics"
            lbMethod: "rr"
            maxTries: 3
            maxBatchSize: 0
            keepAliveInterval: "10s"
            concurrencyLimit: 0
            maxIdleConnsPerHost: 1000
            fallback_version: "v1.61.1"
            backendOptions:
                step: "60"
                start: "-5m"
                max_points_per_query: 5000
            timeouts:
                find: "2s"
                render: "50s"
                connect: "200ms"
            servers:
                 - "http://vmselect-cluster.internal/select/0/prometheus"                                                                                     
```
