### ISSUE TITLE
[BUG] Send multiple targets in MultiFetchRequest

### ISSUE THREAD

**Issue by jonasbleyl** [go-graphite/carbonapi#631]
**Describe the bug**
When querying CarbonAPI with multiple targets it will sequentially send off a request for each target.

Can CarbonAPI be configured to simply send a single request containing an array of the targets in the MultiFetchRequest?

**CarbonAPI Version**
main

**CarbonAPI Configuration:**
```
listen: "localhost:9090"
upstreams:
  backendsv2:
    backends:
      - protocol: "carbonapi_v3_pb"
        maxBatchSize: 0
        lbMethod: "rr"
        servers:
          - "http://localhost:5000"
```

**Additional context**

I've implemented the `carbonapi_v3_pb` protocol in a custom backend but `MultiFetchRequest.Metrics` will only ever have a size of 1 no matter how I configure CarbonAPI.

Alternatively, is there a way to query for the targets for a single request in parallel?
