### ISSUE TITLE
[BUG] Duplicated series with VictoriaMetrics backend

### ISSUE THREAD

**Issue by keliss** [go-graphite/carbonapi#646]
**Describe the bug**
Hi. Any metric queried from carbonapi results in multiple absolutely identical series with the same name. The number of duplicates seems to depend on whether there were any data merges in VictoriaMetrics (e.g. the number of duplicates can be 5, and after forcing a merge it reduces to 2).

**CarbonAPI Version**
carbonapi-0.15.4~1-1

**Logs**
Literally any metric and request should reproduce the issue, but let me know if request-response logs are still needed.

**CarbonAPI Configuration:**
```
listen: "0.0.0.0:8182"
cache:
  type: "mem"
  size_mb: 0
  defaultTimeoutSec: 60
cpus: 0
tz: ""
graphite:
  host: "localhost:2003"
  interval: "60s"
  prefix: "carbon.api"
  pattern: "{prefix}.{fqdn}"
pidFile: ""
logger:
  - logger: ""
    file: "/var/log/carbonapi/carbonapi-1.log"
    level: "warn"
    encoding: "console"
upstreams:
  buckets: 10
  slowLogThreshold: 7s
  timeouts:
    find: "3s"
    render: "15s"
    connect: "200ms"
  keepAliveInterval: "30s"
  maxIdleConnsPerHost: 1000
  backendsv2:
    backends:
      - groupName: "victoriametrics"
        protocol: "prometheus" # also tried the victoriametrics protocol
        lbMethod: "rr"
        maxTries: 2
        backendOptions:
          step: "1m"
        servers:
          - "http://localhost:8481/select/0/prometheus"
```

**VictoriaMetrics Configuration:**
Cluster version, 1.64.1. Metrics are ingested like this: carbon-c-relay -> vmagent -> vminsert -> vmstorage, and read like this: grafana -> carbonapi -> vmselect -> vmstorage.
```
VMSTORAGE_ARGS="-retentionPeriod=3y -storageDataPath=/opt/vmstorage/data/ -dedup.minScrapeInterval=60s -finalMergeDelay=10080m"
VMINSERT_ARGS="-storageNode=metrics-storage-1:8400"
VMSELECT_ARGS="-storageNode=metrics-storage-1:8401 -search.disableCache -search.denyPartialResponse -search.noStaleMarkers -search.maxUniqueTimeseries=3000000"
VMAGENT_ARGS="-remoteWrite.url=http://localhost:8480/insert/0/prometheus/api/v1/write -promscrape.config=/etc/victoriametrics/prometheus.yml -promscrape.noStaleMarkers -graphiteListenAddr=:2004 -graphiteTrimTimestamp=1m -remoteWrite.maxDiskUsagePerURL=20GB -remoteWrite.showURL -remoteWrite.tmpDataPath=/opt/vmagent/data/"
```
