### ISSUE TITLE
[Question] carbonapi /metrics/find result is different from Graphite webapp

### ISSUE THREAD

**Issue by cynici** [go-graphite/carbonapi#658]
**Describe the bug**

For exactly the same query, the "id" value in /metrics/find results are different between carbonapi and Graphite webapp, e.g.

`"id": "agents"` vs `"id": "carbon.agents"` 

Shall be most grateful for any pointers.

This is my setup:

- go-carbon on 2 servers carbonserver-1, carbonserver-2
- Both carbonapi and webapp run on the same server
- carbonapi uses broadcast method to query both carbonservers
- Graphite webapp CLUSTER_SERVERS = carbonapi:8081

**carbonapi's version**
0.15.4 from stable repo

**Does this happened before**
This is my first time trying out carbonapi as a possible replacement for Graphite webapp

**carbonapi's config**

```
listen: "127.0.0.1:8081"
prefix: ""
useCachingDNSResolver: false
cachingDNSRefreshTime: "1m"
expvar:
  enabled: true
  pprofEnabled: false
  listen: ""
headersToPass:
  - "X-Dashboard-Id"
  - "X-Grafana-Org-Id"
  - "X-Panel-Id"
headersToLog:
  - "X-Dashboard-Id"
  - "X-Grafana-Org-Id"
  - "X-Panel-Id"
define:
  -
    name: "perMinute"
    template: "perSecond({{.argString}})|scale(60)"
notFoundStatusCode: 200
concurency: 1000
cache:
  type: "mem"
  size_mb: 0
  defaultTimeoutSec: 60
cpus: 0
tz: ""
functionsConfig:
maxBatchSize: 100
graphite:
    host: ""
    interval: "60s"
    prefix: "carbon.api"
    pattern: "{prefix}.{fqdn}"
idleConnections:
pidFile: ""
upstreams:
    tldCacheDisabled: false
    buckets: 10
    slowLogThreshold: "1s"
    timeouts:
        find: "2s"
        render: "10s"
        connect: "200ms"
    concurrencyLimitPerServer: 0
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100
    doMultipleRequestsIfSplit: false
    backendsv2:
        backends:
          -
            groupName: "group1"
            protocol: "carbonapi_v3_pb"
            lbMethod: "broadcast"
            maxTries: 3
            maxBatchSize: 100
            keepAliveInterval: "10s"
            concurrencyLimit: 0
            maxIdleConnsPerHost: 1000
            forceAttemptHTTP2: false
            doMultipleRequestsIfSplit: false
            timeouts:
                find: "2s"
                render: "50s"
                connect: "200ms"
            servers:
              - "http://carbonserver-1:8070"
              - "http://carbonserver-2:8070"
    graphite09compat: false
graphTemplates: "/etc/carbonapi/graphTemplates.example.yaml"
expireDelaySec: 600
```

**backend software and config**
go-carbon 0.15.4 carbonserver, also from stable repo

**Query that causes problems**

```
/metrics/find/?query=carbon.*&format=treejson&path=carbon&node=carbon
```

Compare the "id" value below

Result from carbonapi

```json
[
  {
    "allowChildren": 1,
    "expandable": 1,
    "leaf": 0,
    "id": "agents",
    "text": "agents",
    "context": {}
  },
  {
    "allowChildren": 1,
    "expandable": 1,
    "leaf": 0,
    "id": "api",
    "text": "api",
    "context": {}
  },
  {
    "allowChildren": 1,
    "expandable": 1,
    "leaf": 0,
    "id": "relays",
    "text": "relays",
    "context": {}
  }
]
```

Result from Graphite webapp

```json
[
  {
    "text": "agents",
    "expandable": 1,
    "leaf": 0,
    "id": "carbon.agents",
    "allowChildren": 1
  },
  {
    "text": "api",
    "expandable": 1,
    "leaf": 0,
    "id": "carbon.api",
    "allowChildren": 1
  },
  {
    "text": "relays",
    "expandable": 1,
    "leaf": 0,
    "id": "carbon.relays",
    "allowChildren": 1
  }
]
```
