### ISSUE TITLE
[BUG] Data returned from carbonapi is not consistent

### ISSUE THREAD

**Issue by cxfcxf** [go-graphite/carbonapi#684]
**Describe the bug**
Let's say we run two metrics queries in one dashboard
1. `metrics.FRP[PPP]-ADE*-IAD[23].*_*.impression_log_DEBUG_FIELD_VPS_COUNT`
2. `metrics.FRP[PP]-ADE*-IAD[23].*_*.impression_log_DEBUG_FIELD_VPS_COUNT`

They should produce the same amount of data in certain timeframe, so i construct the following queries and run them sequentially
one
```bash
~ > FROM=1661708062;curl -s "http://carbonapi/render?target=metrics.FRP\[PPP\]-ADE*-IAD\[23\].*_*.impression_log_DEBUG_FIELD_VPS_COUNT&target=metrics.FRP\[PP\]-ADE*-IAD\[23\].*_*.impression_log_DEBUG_FIELD_VPS_COUNT&from=${FROM}&until=-180s&format=json" | jq '.[].target' > total_server_returned && wc -l total_server_returned
1746 total_server_returned
```
two
```bash
 ~ > FROM=1661708063;curl -s "http://carbonapi/render?target=metrics.FRP\[PPP\]-ADE*-IAD\[23\].*_*.impression_log_DEBUG_FIELD_VPS_COUNT&target=metrics.FRP\[PP\]-ADE*-IAD\[23\].*_*.impression_log_DEBUG_FIELD_VPS_COUNT&from=${FROM}&until=-180s&format=json" | jq '.[].target' > total_server_returned && wc -l total_server_returned
1746 total_server_returned
```
three
```bash
 ~ > FROM=1661708064;curl -s "http://carbonapi/render?target=metrics.FRP\[PPP\]-ADE*-IAD\[23\].*_*.impression_log_DEBUG_FIELD_VPS_COUNT&target=metrics.FRP\[PP\]-ADE*-IAD\[23\].*_*.impression_log_DEBUG_FIELD_VPS_COUNT&from=${FROM}&until=-180s&format=json" | jq '.[].target' > total_server_returned && wc -l total_server_returned
1346 total_server_returned
```
as you can see, the 3rd one returned 1346 servers instead of 1746 which totally messed up the metrics,
when look at logs, all showing `"metrics_in_response":873`
so it prob means the return carbonapi gets from go-carbon are 873*2 which is totally right, but somehow after carbonapi processed result from go-carbon and returned my query request, it would sometime cut some of result out, the number gets cut out are random.

**CarbonAPI Version**
What's the CarbonAPI version you are running?
carbonapi-0.15.5~1-1.x86_64

Does this issue reproducible on current master?
i havent build master, but 0.15.5 is latest i can find

**Logs**
If applicable, add logs (please use log level debug) that shows the whole duration of the request. Request can be identified by UUID if needed.
the log is huge.  1 query is about 81M big, so i cant paste here
some piece here that actually return as wrong number but in log shows 873 which is totally right
```bash
carbonapi.log:{"level":"DEBUG","timestamp":"2022-08-30T14:06:19.960-0700","logger":"zipper","message":"got response (after merge)","type":"broadcastGroup","groupName":"root","type":"fetch","request":["metrics.FRP[PPP]-ADE*-IAD[23].*_*.impression_log_DEBUG_FIELD_VPS_COUNT"],"carbonapi_uuid":"fa0e84f5-44db-4b4c-bc7b-7ce2bbdd433a","multi_fetch":false,"backend_name":"go-carbon-group1","metrics_in_response":873,"errors_count":0,"timeouts_count":0,"render_requests_count":351,"render_errors_count":0,"render_timeouts_count":0,"zipper_requests_count":0,"total_metric_count":0,"servers_count":0,"failed_servers_count":0}
carbonapi.log:{"level":"DEBUG","timestamp":"2022-08-30T14:06:19.960-0700","logger":"zipper","message":"got some fetch responses","type":"broadcastGroup","groupName":"root","type":"fetch","request":["metrics.FRP[PPP]-ADE*-IAD[23].*_*.impression_log_DEBUG_FIELD_VPS_COUNT"],"carbonapi_uuid":"fa0e84f5-44db-4b4c-bc7b-7ce2bbdd433a","backends_count":1,"response_count":1,"have_errors":false,"errors":null,"metrics_in_response":873}
carbonapi.log:{"level":"DEBUG","timestamp":"2022-08-30T14:06:21.547-0700","logger":"zipper","message":"got response (after merge)","type":"broadcastGroup","groupName":"root","type":"fetch","request":["metrics.FRP[PP]-ADE*-IAD[23].*_*.impression_log_DEBUG_FIELD_VPS_COUNT"],"carbonapi_uuid":"fa0e84f5-44db-4b4c-bc7b-7ce2bbdd433a","multi_fetch":false,"backend_name":"go-carbon-group1","metrics_in_response":873,"errors_count":0,"timeouts_count":0,"render_requests_count":351,"render_errors_count":0,"render_timeouts_count":0,"zipper_requests_count":0,"total_metric_count":0,"servers_count":0,"failed_servers_count":0}
carbonapi.log:{"level":"DEBUG","timestamp":"2022-08-30T14:06:21.547-0700","logger":"zipper","message":"got some fetch responses","type":"broadcastGroup","groupName":"root","type":"fetch","request":["metrics.FRP[PP]-ADE*-IAD[23].*_*.impression_log_DEBUG_FIELD_VPS_COUNT"],"carbonapi_uuid":"fa0e84f5-44db-4b4c-bc7b-7ce2bbdd433a","backends_count":1,"response_count":1,"have_errors":false,"errors":null,"metrics_in_response":873)
```

**CarbonAPI Configuration:**
Please include carbonapi config file that you are using (please replace all information you don't want to share, like domain names or IP addresses).
```yaml
listen: ":80"

headersToPass:
  - "X-Dashboard-Id"
  - "X-Grafana-Org-Id"
  - "X-Panel-Id"
concurency: 2000
cache:
   type: "mem"
   size_mb: 0
   defaultTimeoutSec: 60
   memcachedServers:
       - "127.0.0.1:11211"
cpus: 0
tz: ""

functionsConfig:
    graphiteWeb: /etc/carbonapi/graphiteWeb.yaml
    timeShift: /etc/carbonapi/timeShift.yaml
maxBatchSize: 100
graphite:
    host: "graphite:3003"
    interval: "60s"
    prefix: "carbon.api"
    pattern: "{prefix}.{fqdn}"
idleConnections: 10
pidFile: ""
upstreams:
    tldCacheDisabled: false
    buckets: 10
    slowLogThreshold: "1s"
    timeouts:
        find: "2s"
        render: "10s"
        connect: "200ms"
    concurrencyLimitPerServer: 0
    keepAliveInterval: "30s"
    maxIdleConnsPerHost: 100
    # backends:
    #    - "http://127.0.0.1:8080"
    backendsv2:
        backends:
          -
            groupName: "go-carbon-group1"
            protocol: "carbonapi_v3_pb"
            lbMethod: "broadcast"
            maxTries: 3
            maxBatchSize: 100
            keepAliveInterval: "10s"
            concurrencyLimit: 0
            maxIdleConnsPerHost: 1000
            timeouts:
                find: "2s"
                render: "10s"
                connect: "200ms"
            servers:
                - "http://10.71.228.11:8080"
                - bunch of servers, like 20 of them
    graphite09compat: true
graphTemplates: /etc/carbonapi/graphTemplates.yaml
expireDelaySec: 10
logger:
    - logger: ""
      file: "/var/log/carbonapi/carbonapi.log"
      level: "debug"
      encoding: "json"
```

**Simplified query (if applicable)**
Please provide a query that triggered the issue, ideally narrowed down to smallest possible set of functions.
the query is very simple, please beware  that FROM is a variable
```bash
"http://carbonapi/render?target=metrics.FRP\[PPP\]-ADE*-IAD\[23\].*_*.impression_log_DEBUG_FIELD_VPS_COUNT&target=metrics.FRP\[PP\]-ADE*-IAD\[23\].*_*.impression_log_DEBUG_FIELD_VPS_COUNT&from=${FROM}&until=-180s&format=json"
```

**Additional context**
this is totally reproducable, it just need to get run a lot of times, say 20 and make sure its not hitting the cache of carbonapi

i can provide the debug log 81M which only consists the query that rendered buggy if needed
