### ISSUE TITLE
[BUG] Grafana can't show metrics which directory names include curly brackets { } if maxBatchSize not 0

### ISSUE THREAD

**Issue by Knud3** [go-graphite/carbonapi#752]
`If not 0, carbonapi will do find request to determine how many metrics matches criteria and only then will fetch them, not more than maxBatchSize per request.`

Not sure if it is find request or does `maxBatchSize` do something else for render request.

Maybe related to #29 and/or #746 and/or #661.

Have tried with
```
unicodeRangeTables:
  - "all"
```

Tried with escaping curly brackets in directory names `Bad Request: Bad Request Target : foo.bar\{topic\}.* Parsed so far : foo.bar\{topic\ Could not parse : }.*`

HTTP clients and servers that use path parameters often represent these path parameters as `{variable}`, e.g. `/reports/{date}` . It would be great to be able to use this same format in the graphs to refer to these URL endpoints.

Settings in use with newest `v0.16.0-patch2` and go-carbon `v0.16.2`:

```
listen: "0.0.0.0:8081"
prefix: ""
expvar:
  enabled: false
  pprofEnabled: false
  listen: ""
notFoundStatusCode: 404
unicodeRangeTables:
  - "all"
cache:
  type: "mem"
  size_mb: 1024
  defaultTimeoutSec: 600
backendCache:
  type: "null"
cpus: 0
tz: ""
functionsConfig:
  graphiteWeb: /etc/carbonapi/graphiteWeb.yaml
  timeShift: /etc/carbonapi/timeShift.yaml
graphite:
  host: "carbon-tcp:2003"
  interval: "60s"
  prefix: "carbon.api.gt-grafana-stg"
  pattern: "{prefix}.{fqdn}"
concurency: 5000
idleConnections: 100
pidFile: ""
upstreams:
  graphite09compat: false
  buckets: 10
  concurrencyLimitPerServer: 0
  keepAliveInterval: "10s"
  maxIdleConnsPerHost: 100
  timeouts:
    find: "120s"
    render: "120s"
    connect: "30s"
  backendsv2:
    backends:
      -
        groupName: "go-carbon"
        protocol: "carbonapi_v3_pb"
        lbMethod: "broadcast"
        maxTries: 3
        maxBatchSize: 5000
        concurrencyLimit: 0
        servers:
            - "http://carbonserver:8080"
expireDelaySec: 600
logger:
- logger: ""
  file: "stderr"
  level: "warn"
  encoding: "console"
  encodingTime: "iso8601"
  encodingDuration: "seconds"
- logger: ""
  file: "stdout"
  level: "info"
  encoding: "console"
  encodingTime: "iso8601"
  encodingDuration: "seconds"
- logger: "slow"
  level: "error"
```
