### ISSUE TITLE
[BUG] /find 400 Bad Request when % is first character in metric name

### ISSUE THREAD

**Issue by brobotic** [go-graphite/carbonapi#803]
**Describe the bug**
/find appears to return HTTP 400 Bad Request when a metric name starts with %.

The metrics /render okay in Grafana after the HTTP 400, but I'm hesitant to roll this out to end-users with this error.

Example queries:
E4_Environment.*.Processor._Total.%_User_Time.wsp
Environment.SERVER123.Processor._Total.%_User_Time.wsp

/find will succeed for each part of the metric until `%_User_Time.wsp`

```
username@carbonapi:/whisper$ curl http://127.0.0.1/metrics/find/?query=Environment.*.Processor.*
[{"allowChildren":1,"expandable":1,"leaf":0,"id":"Environment.*.Processor._Total","text":"_Total","context":{}}]

username@carbonapi:/whisper$ curl http://127.0.0.1/metrics/find/?query=Environment.*.Processor._Total.*
[{"allowChildren":0,"expandable":0,"leaf":1,"id":"Environment.*.Processor._Total.%_User_Time","text":"%_User_Time","context":{}}]

username@carbonapi:/whisper$ curl http://127.0.0.1/metrics/find/?query=Environment.*.Processor._Total.%_User_Time.wsp
missing parameter `query`
```

Could not reproduce issue after copying metric to the same path but without the %_ i.e. `User_Time.wsp`

**CarbonAPI Version**
Tried `v0.16.1-1-g3eb7` and `v0.16.1`

**CarbonAPI Configuration:**
```
listen: ":8080"
concurrencyLimit: 0
cache:
  type: "null"
  size_mb: 0
  defaultTimeoutSec: 60
cpus: 0
tz: ""
graphite:
  host: "graphite01:2013"
  interval: "60s"
  prefix: "carbon.api"
  pattern: "{prefix}.{fqdn}"
keepAliveInterval: "30s"
pidFile: ""
upstreams:
  buckets: 10
  timeouts:
    find: "60s"
    render: "60s"
    connect: "200ms"
  maxIdleConnsPerHost: 100
  graphite09compat: false
  backendsv2:
    backends:
      -
        groupName: "cluster1"
        protocol: "auto"
        maxBatchSize: 1000
        maxTries: 3
        lbMethod: "broadcast"
        servers:
          - "http://graphite11:8080"
          - "http://graphite12:8080"
          - "http://graphite13:8080"
          - "http://graphite14:8080"
      -
        groupName: "cluster2"
        protocol: "auto"
        maxBatchSize: 1000
        maxTries: 3
        lbMethod: "broadcast"
        servers:
          - "http://graphite21:8080"
          - "http://graphite22:8080"
          - "http://graphite23:8080"
          - "http://graphite24:8080"
expireDelaySec: 10
notFoundStatusCode: 200

unicodeRangeTables:
  - "all"

headersToLog:
  - "X-Panel-Id"
  - "X-Dashboard-Id"
  - "X-Real-Ip"
  - "X-Webauth-User"
logger:
  - logger: ""
    file: "stderr"
    level: "warn"
    encoding: "console"
    encodingTime: "iso8601"
    encodingDuration: "seconds"
  - logger: ""
    file: "/var/log/carbonapi/carbonapi.log"
    level: "info"
    encoding: "json"
```

**Backend response (if possible)**
HTTP 400 Bad Request - missing parameter `query`

Please let me know if I can provide any additional information. Thank you!
