### ISSUE TITLE
[BUG] force_min_step_interval on victoriametrics backend is ignored

### ISSUE THREAD

**Issue by mlausch** [go-graphite/carbonapi#856]
**Describe the bug**
The "force_min_step_interval" option is at least in the victoriaMetrics backend ignored.

As I saw on the code, if the value is higher than the interval (stop - start) the step size shold be used for the query on the backend. But this is not the case.

**CarbonAPI Version**
0.16.0
Also on the Master the bug is present.

**CarbonAPI Configuration:**
```
    backendsv2:
        backends:
          - groupName: "victoriametrics"
            protocol: "victoriametrics"
            lbMethod: "broadcast"
            maxTries: 3
            maxBatchSize: 0
            keepAliveInterval: "10s"
            concurrencyLimit: 0
            maxIdleConnsPerHost: 1000
            backendOptions:
                step: "60"
                start: "-43200m"
                max_points_per_query: 5000
                probe_version_interval: "600s"
                fallback_version: "v0.0.0"
                force_min_step_interval: "8800h"
                # vmClusterTenantID: "0" # use vmClisterTenantID for VM-cluster only
            timeouts:
                find: "2s"
                render: "50s"
                connect: "200ms"
            servers:
              - "http://127.0.0.1:8482"
              - "http://127.0.0.1:8483"

```
**Simplified query (if applicable)**
query parameter send from grafana to carbonapi:
`target=some.metric&from=1730980363&until=1738756365&format=json&maxDataPoints=1378`

query parameter send to victoriametrics
`end=1738756365&max_lookback=7200s&query=%7B__graphite__%3D%22some.metric%22%7D&start=1730980363&step=7200s`

as you can see, the step size is way bigger than the expected "60s" which is the min step size configured in the carbonapi.conf
